name: Jen Watley Nelson
favicon: null
layout_spectrum: 0.22903640661388636
typography_spectrum: 0.26022826530970633
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.12584218312986195
  lightness: 0.5328794969245791
  saturation: 0.1216718084178865
  rhythmicContrast: 0.21116032195277512
purpose: []
